# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b94000a42f9211d99ee2b197cb9e51cf5ef3ab45b4fb26a44fb07eb0a20834fa580a8eceda30a6bcda6f8c7135feea11869fa41a8a32264c982f5aba0bea5a8

test:
  secret_key_base: 6b82a03a0d957436afb616ca600fee16de1aac2bbb322d3afcb781d1c1e0dfeb9ce4af9df735ba8081247919dd4cdf0fd54aea91e09894c968f328434a57ca5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
